# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("operacao", models.CharField(max_length=8)),
                ("resultado", models.CharField(max_length=64)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "calculo",
                "verbose_name_plural": "calculos",
                "ordering": ["-id"],
            },
        ),
    ]
